from tkinter import *
import sqlite3
root=Tk()
root.title('CALCULATOR')
root.geometry("375x280")
root.resizable(0,0)
root.configure(bg='black')
a=StringVar()
def show(c):
        a.set(a.get()+c)
def equ():
    try:
        con=sqlite3.connect('calculator.db')
        cursor=con.cursor()
        query="insert into CALC values('%s','%s')"
        cursor.execute(query %(a.get(),eval(a.get())))
        con.commit()
    except sqlite3.DatabaseError as e:
        if con:
            print(e)
            con.rollback()
    finally:
        if cursor:
            cursor.close()
        if con:
            con.close()
    a.set(eval(a.get()))
e1=Entry(root,font=('Arial',20),borderwidth=10,justify='right',textvariable=a)
e1.place(x=0,y=0,height=70,width=375)
zero=Button(root,text='0',font=('Arial',15),command=lambda:show("0"))
zero.place(x=0,y=230,height=40,width=70)
one=Button(root,text='1',font=('',15),command=lambda:show("1"))
one.place(x=0,y=180,height=40,width=70)
two=Button(root,text='2',font=('Arial',15),command=lambda:show("2"))
two.place(x=70,y=180,height=40,width=70)
three=Button(root,text='3',font=('Arial',15),command=lambda:show("3"))
three.place(x=140,y=180,height=40,width=70)
four=Button(root,text='4',font=('Arial',15),command=lambda:show("4"))
four.place(x=0,y=130,height=40,width=70)
five=Button(root,text='5',font=('Arial',15),command=lambda:show("5"))
five.place(x=70,y=130,height=40,width=70)
six=Button(root,text='6',font=('Arial',15),command=lambda:show("6"))
six.place(x=140,y=130,height=40,width=70)
seven=Button(root,text='7',font=('Arial',15),command=lambda:show("7"))
seven.place(x=0,y=80,height=40,width=70)
eight=Button(root,text='8',font=('Arial',15),command=lambda:show("8"))
eight.place(x=70,y=80,height=40,width=70)
nine=Button(root,text='9',font=('Arial',15),command=lambda:show("9"))
nine.place(x=140,y=80,height=40,width=70)
clear1=Button(root,text='AC',font=('Arial',15),command=lambda:a.set(""))
clear1.place(x=70,y=230,height=40,width=140)
add=Button(root,text='+',font=('Arial',20),command=lambda:show("+"))
add.place(x=220,y=180,height=80,width=70)
sub=Button(root,text='-',font=('Arial',20),command=lambda:show("-"))
sub.place(x=220,y=130,height=40,width=70)
mod=Button(root,text='%',font=('Arial',20),command=lambda:show("%"))
mod.place(x=220,y=80,height=40,width=70)
equ=Button(root,text='=',font=('Arial',20),command=equ)
equ.place(x=290,y=220,height=40,width=70)
div=Button(root,text='/',font=('Arial',20),command=lambda:show("/"))
div.place(x=290,y=180,height=40,width=70)
mul=Button(root,text='X',font=('Arial',20),command=lambda:show("*"))
mul.place(x=290,y=130,height=40,width=70)
fdiv=Button(root,text='//',font=('Arial',20),command=lambda:show("//"))
fdiv.place(x=290,y=80,height=40,width=70)
root.mainloop()